global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-enterprise-accelerator-pci
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-enterprise-accelerator-pcit1:
    parameter_input: quickstart-enterprise-accelerator-pci-example-params1.json
    template_file: quickstart-enterprise-accelerator-pci-example1.template
  quickstart-enterprise-accelerator-pcit2:
    parameter_input: quickstart-enterprise-accelerator-pci-example-params2.json
    template_file: quickstart-enterprise-accelerator-pci-example2.template
